language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_install:
 - composer install --dev --prefer-source
 - wget http://get.sensiolabs.org/php-cs-fixer.phar && chmod u+x php-cs-fixer.phar

script:
 - ant

after_script:
 - wget https://scrutinizer-ci.com/ocular.phar
 - php ocular.phar code-coverage:upload --format=php-clover build/coverage.clover

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

notifications:
  email: false
